### ISSUE TITLE
Google search for Shining Force 3DS link is 404

### ISSUE THREAD

**Issue by Murphinator2000** [jaredhaight/lgod#17] opened 2013-05-05 03:39 UTC
I did a search for Shining Force 3DS recently... if you go to the 2nd search page you will find the LGOD link.  It is pointing to: 
http://www.livegeekordie.com/index.php/games/handheld/1043-bring-shining-force-the-sword-of-hajya-to-3ds

This is a 404.  Can this be fixed?  Otherwise we will probably get less views from Google in the end.

**Comment by jaredhaight** [comment] 2013-05-05 04:57
This is a duplicate of GH-10

**Closed as completed** 2013-05-05 04:57 UTC
Labels: duplicate

**Comment by jaredhaight** [comment] 2013-05-05 04:59
On closer look, the URL is a little different, I'll add it to GH-10
